### ISSUE TITLE
bad assumption in translatePolicy

### ISSUE THREAD

**Issue by ccasin** [draperlaboratory/hope-policy-tool#9]
In GenRuleC.hs, the translatePolicy case for RuleClause generates C code that implicitly assumes that policySuccess is 1.  Remove this assumption.

**Comment by amstrnad** [comment]
As far as I can tell, the policy result is always compared to a POLICY_SUCCESS somehow or other. I found one place where the value of `policyResult` includes `1 && ...`, but it turns out that that value was entirely unrelated to the actual result. See commit 554e8a7.
 
My concern is that I've found the values for success/implicit fail/explicit fail defined _3_ separate places. At the moment, they're all the same, but it's not hard to imagine one of them getting missed if it needs to be updated. Commit 39acf10 removes extra definitions.

**Comment by ccasin** [comment]
With respect to the redefinition of POLICY_SUCCESS and friends: I agree this is a problem.  I suggest going a step farther - remove the local variables `policySuccess` and friends from `policy_rule.c` completely and replace their uses with the macros.  (Unless I'm missing something about why those variables are defined.)

Once that's done, the variables change is ready for a pull request.  Make a branch here whose name begins with `pr-` that has the change, and a corresponding branch with the same name in `hope-src`, with an updated submodule reference.  That should kick off the CI.

Will look at 554e8a7 next

**Comment by ccasin** [comment]
Looking at 554e8a7: I think this is a symptom of a bigger problem.  The comment in `GenRuleC.hs` describing the behavior of `translatePolicy` claims: that the returned statements will set the variable `pass` to the result of the policy.  But actually the code does not do that - it just returns the result.  The comment above `translateRuleResult` later describes the actual behavior.

I also no longer see any cases where the code assumes POLICY_SUCCESS is 1.

I'm closing this ticket and will make two new tickets for the two issues you found.
